travis:
  secure:
    BINSTAR_TOKEN: DJIN8cJSlc8XWsALf5RX1Cdko6xnzs8ZUkjECs/j7uieaozrsSNk1FcvlWpxXOEdkdGYbuVV5qsO0XMq68Vv7teVqeCOkXETnJ0NwDbTwisZmed8ZJdJDyeFjrdPLAUqjeIXgUyEqS7JgdA1tIZyzNUvCtpesoCzeHLtd58HGLUr/f1DJ03dBr/Y2N7okrLX/JvgPRNslocdMbrYzHEKebr3+y2IkNmojLSQceRqt0VDlTBUdBfzN1sIrO8Jf/dqWoZ5YtSBNMb1svuXYLbJe6nlXJe6uOtfaOVnWjt36RXSYNG6sd+HcHWBsDS4KFDEZtm0LC5KgsiFUNcUwInIOXgK2ZpmjZiPMolBnp2uSe0XFpEIeZBGJzFfxDHKbwNoJZHweDzVDCp1kSb5ZmpXQ0Do69ISPhP5IlCiLuJrkbzkIcVWmjmLU2ymZWZQodp7rBRXabjQd77RJbVctleLSxoYxbmW4w9sQ5FQ4Hio9jFOf512HKhCgTKIGzBnqmTW/8ZJeySFdGJfgj3Nax61rk6894bZQv5Fq/krN8L3BjPuHQgZvHMZynpyCXcZpzARlfcF2fjwIDheQHzJqGLNjdQTzLhROA5BlsexqvSvg1cYOKuquzCqiks8laClrD3/YFqechJGhZ1f/drOqeQXaMQ4Oh+LQnj7lTpOfTZY6dQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
